---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"

  pre_tasks:
    - name: "Set test facts"
      ansible.builtin.set_fact:
        vm_name: ansible_molecule_snowdrop_openstack_test

    - name: Set authentication vars
      ansible.builtin.set_fact:
        rhos_auth:
          auth_url: "{{ openstack_auth.openstack_os_auth_url }}"
          password: "{{ openstack_auth.openstack_console_password }}"
          project_domain_name: "{{ openstack_auth.openstack_project_domain }}"
          project_name: "{{ openstack_auth.openstack_project_name }}"
          username: "{{ openstack_auth.openstack_console_user }}"
          user_domain_name: "{{ openstack_auth.openstack_user_domain }}"
        rhos_auth_type: v3password

    - name: Include default vars
      ansible.builtin.include_vars:
        file: defaults/main.yml

  tasks:

    - name: "Delete OpenStack VM"
      ansible.builtin.include_role:
        name: "openstack_vm"
      vars: 
        state: "absent"

    - name: "Delete host from known hosts"
      ansible.builtin.known_hosts:
        name: "{{ hostvars[vm_name]['ansible_ssh_host'] }}"
        state: absent
      when: "hostvars[vm_name]['ansible_ssh_host'] is defined"
      failed_when: false
    # Developer must implement.

    # Mandatory configuration for Molecule to function.

    - name: Populate instance config
      ansible.builtin.set_fact:
        instance_conf: {}

    - name: Dump instance config
      ansible.builtin.copy:
        content: |
          # Molecule managed

          {{ instance_conf | to_json | from_json | to_yaml }}
        dest: "{{ molecule_instance_config }}"
        mode: 0600
      when: server.changed | default(false) | bool

...
